### ISSUE TITLE
Errors fetching in log

### ISSUE THREAD

**Issue by MadOtis** [ThomasPrior/2minersInfo#3]
**Describe the issue**
Installed following README and added sensor 2 different ways (but only one-at-a-time):
`- platform: 2minersinfo
  miner_address: "0xF21[obfuscated]"
  currency_name: USD
  name_override: "2Miners Wallet"
  token: eth
  solo: false`
-and-
`- platform: 2minersinfo
  miner_address: !secret twominers_wallet
  currency_name: USD
  name_override: "2Miners Wallet"
  token: eth
  solo: false`

And only get this every few seconds in the logs:
`2022-05-19 16:10:56 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.2minersinfo_exodus_wallet fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/2minersinfo/sensor.py", line 348, in _update
    self._paid_on = datetime.fromtimestamp(int(r['payments'][0]['timestamp'])).strftime('%d-%m-%Y %H:%M')
TypeError: 'NoneType' object is not subscriptable`

**To Reproduce**
1. Add 2minersinfo plugin via HACS
2. Restart HA
3. Add sensor to sensors.yaml (which is included in configuration.yaml)
4. Restart HA
5. Use "developer tools" to see what data is returned by the sensor only to see:
`active_workers: null
current_hashrate: null
last_update: null
unpaid: null
amount: null
txhash: null
paid_on: null
single_coin_in_local_currency: null
unpaid_in_local_currency: null
current_hashrate_mh_sec: null
unit_of_measurement: ​
icon: mdi:ethereum`
with a state of "unknown"
6. Look at logs and see the above trace.

**Expected behaviour**
Valid data coming from the plugin/sensor

---
name: New EthermineInfo Issue
about: Report issues with EthermineInfo with this form
title: "[ISSUE]"
labels: bug
assignees: ThomasPrior

**Comment by ThomasPrior** [comment]
Hey @MadOtis, have you ever had a payout from 2miners?

**Comment by MadOtis** [comment]
No, not yet.  I just switched one worker over to 2miners (off of Hive).

**Comment by ThomasPrior** [comment]
> No, not yet.  I just switched one worker over to 2miners (off of Hive).

Could you try replacing the sensor.py in your current install with the one in the Dev branch?

**Comment by MadOtis** [comment]
Sure thing.  I'll do it this afternoon after work.

**Comment by MadOtis** [comment]
Switching to the DEV branch version of sensor.py made "some" progress, but still failing.  This time with:

> `Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
>     raise exc
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
>     result = method(*args, **kwargs)
>   File "/config/custom_components/2minersinfo/sensor.py", line 350, in _update
>     if len(r['payments']):
> TypeError: object of type 'NoneType' has no len()`

**Comment by ThomasPrior** [comment]
Think I've got it this time - can you try the latest sensor.py in the DEV branch again please?

I appreciate your time and effort to help me nail this down.

**Comment by MadOtis** [comment]
Same result:

```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
>     raise exc
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
>     result = method(*args, **kwargs)
>   File "/config/custom_components/2minersinfo/sensor.py", line 350, in _update
>     if len(r['payments']):
> TypeError: object of type 'NoneType' has no len()
```

I'm not a python programmer (Ask me a golang question and I'm your guy), but is there a way to check the "r" map for the inclusion of the 'payment' key if it exists?  It looks like the 'len' function is failing when trying to deconstruct a non-existent map value.   FWIW, if I comment out lines 350->353, I DO get valid data back in the sensor.

**Comment by ThomasPrior** [comment]
Are either of these possible to help me replicate the issue?

1) Share your wallet address
OR
2) Create a dummy address, mine long enough to show data on 2miners and share that wallet address

I'm contractually obliged not to hold any cryptocurrency so I'm limited on what I can do to test. I had been testing with addresses that had received payouts listed on the dashboard.

In terms of inspecting the data, you can add a print(r) almost anywhere in the data retrieval cycle. Line 332 would work, then you'd just have to inspect the homeassistant log to see the data.

**Comment by ThomasPrior** [comment]
Actually I think I've got it resolved in https://github.com/ThomasPrior/2minersInfo/commit/8bddc536b8e7aa81d87b16eb13102d58b411cab3

Could you please test and confirm @MadOtis ?

**Comment by MadOtis** [comment]
Yes, that solved the issue!

**Comment by ThomasPrior** [comment]
![](https://media.giphy.com/media/ZmuUzqOIEojjnd4tN8/giphy.gif)
