### ISSUE TITLE
[ISSUE] Update for sensor.2minersinfo fails

### ISSUE THREAD

**Issue by andreclemente** [ThomasPrior/2minersInfo#5]
It seems to be related with the coingecko API since this is what I see in logs:

`<title>Access denied | api.coingecko.com used Cloudflare to restrict access</title>`

**Comment by andreclemente** [comment]
I also see this:
`<p>The owner of this website (api.coingecko.com) has banned you temporarily from accessing this website.</p>`

**Comment by ThomasPrior** [comment]
Yep, I'm getting that as well. Not a lot I can do unless Coingecko explain what's going on and the situation over there settles down.

https://twitter.com/coingecko/status/1539179871771197440?t=nISfYjLz5ckaSSvx9RnqlA&s=19

**Comment by ThomasPrior** [comment]
@andreclemente looks like Cloudflare had an outage earlier today. Are you continuing to see issues? Things are clearing up for me.

**Comment by andreclemente** [comment]
Yes, it seems to be fixed now. Thanks.
